/* Santinho Finance V8 — local-first, Safari/PWA friendly. */
(() => {
"use strict";

const DB_NAME="santinho-finance-db",DB_VERSION=1,STORE="app",LS_KEY="santinho-finance-snapshot-v1",SESSION_KEY="santinho-session",SCHEMA=2;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));

const MOTIVATIONS=["Pequenos hábitos, grandes resultados.","Cada real bem direcionado aproxima uma meta.","Controle não é deixar de viver; é escolher para onde o dinheiro vai.","Seu futuro financeiro começa com uma decisão feita hoje.","Registrar um gasto é transformar dinheiro em informação.","Consistência vale mais que perfeição.","Uma meta clara deixa cada economia mais concreta.","Organização financeira também é liberdade.","Antes de gastar, pergunte: isso ajuda sua próxima meta?","Dinheiro organizado dá mais espaço para aproveitar a vida."];

const defaultState=()=>({schema:SCHEMA,credentials:null,profile:{username:"",email:"",avatar:null},transactions:[],goals:[],settings:{theme:"dark",pinHash:null,lastBackupAt:null,privacyAccepted:false},motivationHistory:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
let state=defaultState(),db=null,balanceVisible=true,currentPage="dashboard",toastTimer=null,recognition=null;
const assistant={draft:null,awaiting:null,confirm:false};

function syncViewport(){const h=window.visualViewport?.height||window.innerHeight;if(h)document.documentElement.style.setProperty("--app-vh",`${h}px`);}
function lockPage(v){document.documentElement.classList.toggle("modal-open",v);document.body.classList.toggle("modal-open",v);}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function parseDateKey(k){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(k||"")))return null;const [y,m,d]=String(k).split("-").map(Number);return new Date(y,m-1,d);}
function formatDateKey(k){const d=parseDateKey(k);return d?d.toLocaleDateString("pt-BR"):"Data inválida";}
function monthKey(k){return /^\d{4}-\d{2}-\d{2}$/.test(String(k||""))?String(k).slice(0,7):"";}
function yearKey(k){return /^\d{4}-\d{2}-\d{2}$/.test(String(k||""))?String(k).slice(0,4):"";}
function isFuture(t){return String(t.date)>todayKey();}
function realized(t){return String(t.date)<=todayKey();}
function cmp(a,b){return String(a).localeCompare(String(b));}
function amount(v){if(typeof v==="number")return Math.round(v*100)/100;let s=String(v??"").trim().replace(/\s/g,"").replace(/R\$/gi,"");if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");const n=Number(s);return Number.isFinite(n)?Math.round(n*100)/100:0;}

function openDB(){return new Promise((res,rej)=>{if(!("indexedDB"in window))return rej(new Error("IndexedDB indisponível"));const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});}
function idbGet(k){return new Promise((res,rej)=>{if(!db)return rej();const q=db.transaction(STORE,"readonly").objectStore(STORE).get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function idbSet(k,v){return new Promise((res,rej)=>{if(!db)return rej();const q=db.transaction(STORE,"readwrite").objectStore(STORE).put(v,k);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}

function normalize(raw){
  const base=defaultState();
  const tx=Array.isArray(raw?.transactions)?raw.transactions.filter(Boolean).map(t=>({
    id:t.id||uid("tx"),type:t.type==="income"?"income":"expense",description:String(t.description??"Sem descrição").trim()||"Sem descrição",
    amount:amount(t.amount),category:String(t.category??"Outros").trim()||"Outros",date:/^\d{4}-\d{2}-\d{2}$/.test(String(t.date))?String(t.date):todayKey(),
    note:String(t.note??"").trim(),recurrence:["none","daily","weekly","biweekly","monthly"].includes(t.recurrence)?t.recurrence:"none",
    recurrenceEnd:/^\d{4}-\d{2}-\d{2}$/.test(String(t.recurrenceEnd))?String(t.recurrenceEnd):"",parentId:t.parentId||null,recurrenceId:t.recurrenceId||t.parentId||null
  })):[];
  tx.forEach(t=>{if(t.recurrence!=="none"&&!t.recurrenceId)t.recurrenceId=t.id;});
  const goals=Array.isArray(raw?.goals)?raw.goals.filter(Boolean).map(g=>({id:g.id||uid("goal"),name:String(g.name??"").trim(),target:amount(g.target),current:amount(g.current),deadline:/^\d{4}-\d{2}-\d{2}$/.test(String(g.deadline))?String(g.deadline):"",openedAt:/^\d{4}-\d{2}-\d{2}$/.test(String(g.openedAt))?String(g.openedAt):todayKey(),completedAt:/^\d{4}-\d{2}-\d{2}$/.test(String(g.completedAt))?String(g.completedAt):""})):[];
  return {...base,...raw,schema:SCHEMA,credentials:raw?.credentials?{...raw.credentials}:null,profile:{...base.profile,...raw?.profile},settings:{...base.settings,...raw?.settings},transactions:tx,goals,motivationHistory:Array.isArray(raw?.motivationHistory)?raw.motivationHistory.map(String).slice(-5):[]};
}
async function loadState(){let x=null;try{db=await openDB();x=await idbGet("state")}catch{}if(!x)try{x=JSON.parse(localStorage.getItem(LS_KEY)||"null")}catch{}state=x?normalize(x):defaultState();applyTheme();}
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(LS_KEY,JSON.stringify(state))}catch{toast("Não foi possível salvar localmente.")}if(db)idbSet("state",state).catch(()=>{});}

async function hash(secret,salt){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:150000,hash:"SHA-256"},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function credential(id,pw){const salt=crypto.randomUUID();return{identifier:id.trim().toLowerCase(),salt,passwordHash:await hash(pw,salt)};}
function show(id){["authView","pinView","mainView"].forEach(x=>$("#"+x)?.classList.toggle("hidden",x!==id));$("#voiceAssistant")?.classList.toggle("hidden",id!=="mainView");}
function authMsg(t,e=false){const x=$("#authMessage");if(x){x.textContent=t;x.classList.toggle("error",e)}}
function pinMsg(t,e=false){const x=$("#pinMessage");if(x){x.textContent=t;x.classList.toggle("error",e)}}
function authMode(){const has=!!state.credentials;$("#loginForm")?.classList.toggle("hidden",!has);$("#setupForm")?.classList.toggle("hidden",has);$("#authTitle").textContent=has?"Entrar no Santinho Finance":"Criar seu Santinho Finance";$("#authSubtitle").textContent=has?"A autenticação acontece somente neste aparelho.":"Crie um acesso local. Nenhuma credencial será enviada para a internet.";$("#toggleSetup").textContent=has?"Criar sua conta":"Já tenho uma conta — entrar";}
function authForm(mode){const login=mode==="login";$("#loginForm").classList.toggle("hidden",!login);$("#setupForm").classList.toggle("hidden",login);$("#authTitle").textContent=login?"Entrar no Santinho Finance":"Criar seu Santinho Finance";$("#authSubtitle").textContent=login?"A autenticação acontece somente neste aparelho.":"Crie um acesso local. Nenhuma credencial será enviada para a internet.";$("#toggleSetup").textContent=login?"Criar sua conta":"Já tenho uma conta — entrar";}

async function setup(e){e.preventDefault();const u=$("#setupUsername").value.trim(),em=$("#setupEmail").value.trim(),p=$("#setupPassword").value,p2=$("#setupPassword2").value;if(!u)return authMsg("Informe um nome de usuário.",true);if(p.length<6)return authMsg("Use pelo menos 6 caracteres.",true);if(p!==p2)return authMsg("As senhas não conferem.",true);state.credentials=await credential(em||u,p);state.profile.username=u;state.profile.email=em;save();$("#loginIdentifier").value=em||u;$("#loginPassword").value="";authForm("login");authMsg("Conta criada. Agora entre para continuar.");}
async function login(e){e.preventDefault();const id=$("#loginIdentifier").value.trim().toLowerCase(),p=$("#loginPassword").value,c=state.credentials;if(!c)return authMsg("Nenhuma conta local configurada.",true);const valid=id===c.identifier||id===String(state.profile.username).toLowerCase()||id===String(state.profile.email).toLowerCase();if(!valid)return authMsg("Username/e-mail ou senha inválidos.",true);if(await hash(p,c.salt)!==c.passwordHash)return authMsg("Username/e-mail ou senha inválidos.",true);sessionStorage.setItem(SESSION_KEY,"1");if(state.settings.pinHash){show("pinView");$("#pinInput").value="";setTimeout(()=>$("#pinInput")?.focus(),40)}else enterApp();}
async function verifyPin(e){e.preventDefault();const p=$("#pinInput").value.trim(),cfg=state.settings.pinHash;if(!/^\d{4,6}$/.test(p))return pinMsg("Use de 4 a 6 números.",true);if(!cfg)return enterApp();if(await hash(p,cfg.salt)!==cfg.hash)return pinMsg("PIN incorreto.",true);enterApp();}
function enterApp(){show("mainView");renderAll();if(!state.settings.privacyAccepted)setTimeout(showPrivacy,120);else setTimeout(()=>openAssistant(true),180);}
function logout(){sessionStorage.removeItem(SESSION_KEY);show("authView");authMode();$("#loginPassword").value="";}
function lock(){if(!state.settings.pinHash)return logout();show("pinView");$("#pinInput").value="";setTimeout(()=>$("#pinInput")?.focus(),40);}

function applyTheme(){const t=state.settings.theme||"dark";document.documentElement.classList.toggle("light",t==="light");document.documentElement.dataset.theme=t;if($("#themeSelect"))$("#themeSelect").value=t;}
function changeTheme(v){state.settings.theme=["dark","light","system"].includes(v)?v:"dark";applyTheme();save();}
function navigate(page){if(!["dashboard","analysis","transactions","goals","profile"].includes(page))return;currentPage=page;$$(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${page}`));$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.nav===page));if(page==="dashboard")renderDashboard();if(page==="analysis")renderAnalysis();if(page==="transactions")renderTransactions();if(page==="goals")renderGoals();if(page==="profile")renderProfile();window.scrollTo({top:0,behavior:"smooth"});}
function toast(t){const x=$("#toast");if(!x)return;x.textContent=t;x.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove("show"),2400);}
function chooseMotivation(){const last=state.motivationHistory.at(-1),choices=MOTIVATIONS.filter(x=>x!==last),p=choices[Math.floor(Math.random()*choices.length)];state.motivationHistory=[...state.motivationHistory,p].slice(-5);$("#motivation").textContent=p;save();}

function totals(){const r=state.transactions.filter(realized);const income=r.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),expense=r.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);return{income,expense,balance:income-expense};}
function scheduledExpenses(){return state.transactions.filter(t=>isFuture(t)&&t.type==="expense").reduce((s,t)=>s+t.amount,0);}
function available(){return totals().balance-scheduledExpenses();}

function renderDashboard(){const t=totals(),s=scheduledExpenses(),a=available();$("#welcomeName").textContent=state.profile.username||"amigo";$("#dashboardAvatar").src=state.profile.avatar||"logo-192.png";$("#balanceValue").textContent=balanceVisible?money(a):"••••••";$("#incomeMonth").textContent=balanceVisible?money(t.income):"••••";$("#expenseMonth").textContent=balanceVisible?money(t.balance):"••••";$("#projectedPlanningLine").textContent=balanceVisible?`Saldo cheio: ${money(t.balance)} • Programadas: ${money(s)} • Livre: ${money(a)}`:"Planejamento financeiro oculto.";renderCategories();renderRecent();}
function renderCategories(){const root=$("#categorySummary");const map={};state.transactions.filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8),total=entries.reduce((s,[,v])=>s+v,0);root.innerHTML=entries.length?entries.map(([c,v])=>{const p=total?Math.round(v/total*100):0;return`<div class="category-item"><div class="category-item-head"><span>${esc(c)}</span><b>${money(v)} · ${p}%</b></div><div class="category-bar"><span style="width:${p}%"></span></div></div>`}).join(""):`<div class="empty">Ainda não há despesas registradas.</div>`;}

function txClass(t){return isFuture(t)?"scheduled":t.type==="income"?"income":"expense";}
function recLabel(r){return({daily:"diária",weekly:"semanal",biweekly:"quinzenal",monthly:"mensal"}[r]||"");}
function seriesId(t){return t.recurrenceId||t.parentId||t.id;}
function renderTxList(root,list){if(!list.length){root.innerHTML=`<div class="empty">Nenhuma transação encontrada.</div>`;return;}root.innerHTML=list.map(t=>`<button class="transaction-item transaction-button ${txClass(t)}" data-open-tx="${esc(t.id)}" type="button"><span class="transaction-icon">${isFuture(t)?"◷":t.type==="income"?"↗":"↘"}</span><span class="transaction-main"><b>${esc(t.description)}</b><span>${esc(t.category)} · ${formatDateKey(t.date)}</span><small>${isFuture(t)?"Programado":t.type==="income"?"Renda recebida":"Gasto realizado"}${t.recurrence!=="none"?` · ${recLabel(t.recurrence)}`:""}</small></span><span class="transaction-value">${t.type==="income"?"+":"−"} ${money(t.amount)}</span><span class="transaction-open-hint">›</span></button>`).join("");}
function renderRecent(){renderTxList($("#recentTransactions"),[...state.transactions].sort((a,b)=>cmp(b.date,a.date)).slice(0,6));}
function renderTransactions(){const q=($("#transactionSearch")?.value||"").trim().toLowerCase(),type=$("#transactionType")?.value||"all",status=$("#transactionStatus")?.value||"all";const list=state.transactions.filter(t=>{const text=`${t.description} ${t.category} ${t.note}`.toLowerCase();return(type==="all"||t.type===type)&&text.includes(q)&&(status==="all"||(status==="past"&&realized(t))||(status==="scheduled"&&isFuture(t)))}).sort((a,b)=>cmp(b.date,a.date));renderTxList($("#allTransactions"),list);}

function availableYears(){const set=new Set([todayKey().slice(0,4)]);state.transactions.forEach(t=>set.add(yearKey(t.date)));return[...set].filter(Boolean).sort((a,b)=>Number(b)-Number(a));}
function renderAnalysis(){const ys=availableYears(),selY=$("#analysisYear"),selM=$("#analysisMonth"),months=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];const oldY=selY.value||ys[0],oldM=selM.value||todayKey().slice(5,7);selY.innerHTML=ys.map(y=>`<option value="${y}">${y}</option>`).join("");selY.value=ys.includes(oldY)?oldY:ys[0];selM.innerHTML=months.map((m,i)=>`<option value="${String(i+1).padStart(2,"0")}">${m}</option>`).join("");selM.value=/^\d{2}$/.test(oldM)?oldM:todayKey().slice(5,7);const year=selY.value,month=selM.value,tx=state.transactions.filter(t=>yearKey(t.date)===year&&realized(t)),mi=Array(12).fill(0),me=Array(12).fill(0);tx.forEach(t=>{const i=Number(t.date.slice(5,7))-1;(t.type==="income"?mi:me)[i]+=t.amount});const income=mi.reduce((a,b)=>a+b,0),expense=me.reduce((a,b)=>a+b,0);$("#analysisYearExpense").textContent=money(expense);$("#analysisYearLabel").textContent=year;$("#analysisIncome").textContent=money(income);$("#analysisExpense").textContent=money(expense);$("#analysisBalance").textContent=money(income-expense);$("#analysisAverage").textContent=money(expense/12);renderChart(me);renderCategoriesYear(tx);renderIncomeExpense(mi,me);renderInsights(me);renderTable(mi,me,year);renderInvoice(year,month);}
function renderChart(v){const r=$("#yearlyExpenseChart"),labels=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"],max=Math.max(...v,1);r.innerHTML=v.map((x,i)=>{const h=x?Math.max(6,Math.round(x/max*150)):2;return`<div class="chart-column"><div class="yearly-chart-bar" style="height:${h}px" title="${labels[i]}: ${money(x)}"></div><span class="yearly-chart-label">${labels[i]}</span></div>`}).join("");}
function renderCategoriesYear(tx){const r=$("#yearlyCategoryChart"),m={};tx.filter(t=>t.type==="expense").forEach(t=>m[t.category]=(m[t.category]||0)+t.amount);const e=Object.entries(m).sort((a,b)=>b[1]-a[1]),total=e.reduce((s,[,v])=>s+v,0);r.innerHTML=e.length?e.map(([c,v])=>{const p=total?Math.round(v/total*100):0;return`<div class="category-item"><div class="category-item-head"><span>${esc(c)}</span><b>${money(v)} · ${p}%</b></div><div class="category-bar"><span style="width:${p}%"></span></div></div>`}).join(""):`<div class="empty">Ainda não há gastos neste ano.</div>`;}
function renderIncomeExpense(i,e){const r=$("#incomeExpenseChart"),l=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];r.innerHTML=l.map((x,n)=>{const max=Math.max(i[n],e[n],1);return`<div class="income-expense-row"><div class="income-expense-row-head"><span>${x}</span><span>+${money(i[n])} · −${money(e[n])}</span></div><div class="income-expense-bars"><div class="income-expense-bar income-bar"><span style="width:${i[n]/max*100}%"></span></div><div class="income-expense-bar expense-bar"><span style="width:${e[n]/max*100}%"></span></div></div></div>`}).join("");}
function renderInsights(v){const l=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],nz=v.map((x,i)=>({x,i})).filter(o=>o.x>0),hi=nz.length?Math.max(...nz.map(o=>o.x)):0,lo=nz.length?Math.min(...nz.map(o=>o.x)):0,a=nz.find(o=>o.x===hi),b=nz.find(o=>o.x===lo);$("#highestExpenseMonth").textContent=a?l[a.i]:"—";$("#highestExpenseMonthValue").textContent=money(hi);$("#lowestExpenseMonth").textContent=b?l[b.i]:"—";$("#lowestExpenseMonthValue").textContent=money(lo);}
function renderTable(i,e,year){const l=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];$("#analysisTableBody").innerHTML=l.map((m,n)=>`<tr><td>${m}/${year.slice(2)}</td><td class="income-text">${money(i[n])}</td><td class="expense-text">${money(e[n])}</td><td>${money(i[n]-e[n])}</td></tr>`).join("");}
function renderInvoice(year,month){const r=$("#monthInvoiceList"),tx=state.transactions.filter(t=>yearKey(t.date)===year&&t.date.slice(5,7)===month&&realized(t)),ex=tx.filter(t=>t.type==="expense").sort((a,b)=>cmp(b.date,a.date)),inc=tx.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),sum=ex.reduce((s,t)=>s+t.amount,0);const name=new Date(Number(year),Number(month)-1,1).toLocaleDateString("pt-BR",{month:"long"});$("#monthInvoiceTitle").textContent=`Fatura de ${name} de ${year}`;$("#monthInvoiceIncome").textContent=`Entradas no mês: ${money(inc)}`;$("#monthInvoiceTotal").textContent=money(sum);r.innerHTML=ex.length?ex.map(t=>`<button class="invoice-row" data-open-tx="${esc(t.id)}" type="button"><span><b>${esc(t.description)}</b><small>${formatDateKey(t.date)} · ${esc(t.category)}</small></span><strong>− ${money(t.amount)}</strong></button>`).join(""):`<div class="empty">Nenhum gasto realizado neste mês.</div>`;}

function renderGoals(){const r=$("#goalsList");r.innerHTML=state.goals.length?state.goals.map(g=>{const p=g.target?clamp(g.current/g.target*100,0,100):0;return`<article class="goal-card glass"><div class="goal-head"><b>${esc(g.name)}</b><span>${money(g.current)} / ${money(g.target)}</span></div><div class="goal-progress"><span style="width:${p}%"></span></div><div class="goal-foot"><span>${Math.round(p)}% concluído</span><span>${g.deadline?formatDateKey(g.deadline):"Sem prazo"}</span></div><div class="goal-actions"><button class="btn btn-secondary btn-small" data-goal-add="${esc(g.id)}" type="button">Adicionar valor</button><button class="btn btn-secondary btn-small" data-goal-del="${esc(g.id)}" type="button">Excluir</button></div></article>`}).join(""):`<div class="empty">Crie sua primeira meta financeira.</div>`;}
function renderProfile(){$("#profileUsername").value=state.profile.username||"";$("#profileEmail").value=state.profile.email||"";$("#profileAvatar").src=state.profile.avatar||"logo-192.png";$("#pinStatus").textContent=state.settings.pinHash?"Ativado":"Desativado";$("#configurePin").textContent=state.settings.pinHash?"Alterar PIN":"Configurar";$("#lastBackupStatus").textContent=state.settings.lastBackupAt?`Último backup: ${new Date(state.settings.lastBackupAt).toLocaleString("pt-BR")}`:"Nenhum backup feito ainda.";applyTheme();}
function renderAll(){renderDashboard();renderAnalysis();renderTransactions();renderGoals();renderProfile();}

function closeModal(){const r=$("#modalRoot");if(r){r.classList.add("hidden");r.innerHTML="";lockPage(false);}}
function openModal(title,body,submit){const r=$("#modalRoot");r.innerHTML=`<div class="backdrop"><div class="modal glass"><div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close" type="button">×</button></div><form id="modalForm" class="form-grid">${body}<div class="modal-actions"><button class="btn btn-secondary modal-cancel" type="button">Cancelar</button><button class="btn btn-primary" type="submit">Salvar</button></div></form></div></div>`;r.classList.remove("hidden");lockPage(true);$(".modal-close",r).onclick=closeModal;$(".modal-cancel",r).onclick=closeModal;$("#modalForm",r).onsubmit=async e=>{e.preventDefault();await submit(new FormData(e.currentTarget));};setTimeout(()=>$("input,select,textarea",r)?.focus(),50);}

const CATS=["Moradia","Alimentação","Transporte","Lazer","Estudos","Saúde","Assinaturas","Salário","Freelance","Investimentos","Outros"];
function buildOccurrences(start,rec,end){if(rec==="none")return[start];const out=[];let d=parseDateKey(start),f=parseDateKey(end),guard=0;while(d&&f&&d<=f&&guard<1000){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`);if(rec==="daily")d.setDate(d.getDate()+1);else if(rec==="weekly")d.setDate(d.getDate()+7);else if(rec==="biweekly")d.setDate(d.getDate()+14);else if(rec==="monthly"){const day=d.getDate();d.setMonth(d.getMonth()+1);if(d.getDate()!==day)d.setDate(0)}else break;guard++;}return out.length?out:[start];}
function txForm(type,existing=null,series=false){const t=existing||{type,description:"",amount:0,category:"Outros",date:todayKey(),recurrence:"none",recurrenceEnd:"",note:""};openModal(existing?(series?"Editar recorrência":"Editar transação"):(type==="income"?"Adicionar Renda":"Adicionar Despesa"),`<label>Descrição<input name="description" maxlength="80" required value="${esc(t.description)}"></label><label>Valor (R$)<input name="amount" inputmode="decimal" required value="${t.amount?String(t.amount).replace(".",","):""}"></label><label>Categoria<select name="category">${CATS.map(c=>`<option ${c===t.category?"selected":""}>${esc(c)}</option>`).join("")}</select></label><label>Data<input name="date" type="date" value="${t.date}" required></label><label>Recorrência<select name="recurrence"><option value="none" ${t.recurrence==="none"?"selected":""}>Não repetir</option><option value="daily" ${t.recurrence==="daily"?"selected":""}>Diária</option><option value="weekly" ${t.recurrence==="weekly"?"selected":""}>Semanal</option><option value="biweekly" ${t.recurrence==="biweekly"?"selected":""}>Quinzenal</option><option value="monthly" ${t.recurrence==="monthly"?"selected":""}>Mensal</option></select></label><label id="endWrap" class="${t.recurrence==="none"?"hidden":""}">Repetir até<input name="recurrenceEnd" type="date" value="${t.recurrenceEnd||t.date}"></label><label>Observação<textarea name="note" maxlength="240">${esc(t.note||"")}</textarea></label>`,async fd=>{
  const d=String(fd.get("description")||"").trim(),a=amount(fd.get("amount")),date=String(fd.get("date")||""),rec=String(fd.get("recurrence")||"none"),end=String(fd.get("recurrenceEnd")||"");
  if(!d||!(a>0)||!/^\d{4}-\d{2}-\d{2}$/.test(date))return toast("Revise descrição, valor e data.");if(rec!=="none"&&(!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<date))return toast("Final da recorrência inválido.");
  const common={description:d,amount:a,category:String(fd.get("category")||"Outros"),note:String(fd.get("note")||"").trim(),recurrence:rec,recurrenceEnd:rec==="none"?"":end};
  if(existing&&series){const sid=seriesId(existing),old=state.transactions.filter(x=>seriesId(x)===sid);state.transactions=state.transactions.filter(x=>!old.includes(x));const rid=rec==="none"?null:sid;buildOccurrences(date,rec,end).forEach(x=>state.transactions.push({id:uid("tx"),type:existing.type,date:x,recurrenceId:rid,parentId:null,...common}));}
  else if(existing){Object.assign(existing,{...common,date,recurrenceId:rec==="none"?null:(existing.recurrenceId||existing.id)});}
  else{const rid=rec==="none"?null:uid("txseries");buildOccurrences(date,rec,end).forEach(x=>state.transactions.push({id:uid("tx"),type,date:x,recurrenceId:rid,parentId:null,...common}));}
  save();closeModal();renderAll();toast(existing?"Transação atualizada.":(type==="income"?"Renda adicionada!":"Despesa adicionada!"));
  });$("#modalForm [name=recurrence]")?.addEventListener("change",e=>$("#endWrap")?.classList.toggle("hidden",e.target.value==="none"));
}
function txSeries(t){let s=state.transactions.filter(x=>seriesId(x)===seriesId(t));if(s.length===1&&t.recurrence!=="none")s=state.transactions.filter(x=>x.recurrence!=="none"&&x.type===t.type&&x.description===t.description&&x.amount===t.amount&&x.category===t.category&&x.recurrence===t.recurrence&&x.recurrenceEnd===t.recurrenceEnd);return s.sort((a,b)=>cmp(a.date,b.date));}
function txDetails(id){const t=state.transactions.find(x=>x.id===id);if(!t)return;const s=txSeries(t);const recurring=t.recurrence!=="none";const rows=s.map(x=>`<div class="series-row ${txClass(x)}"><span>${formatDateKey(x.date)}</span><b>${x.type==="income"?"+":"−"} ${money(x.amount)}</b><small>${isFuture(x)?"Programado":x.type==="income"?"Recebido":"Pago"}</small></div>`).join("");openModal("Detalhes da transação",`<div class="transaction-detail-grid"><div><span class="muted">Descrição</span><strong>${esc(t.description)}</strong></div><div><span class="muted">Categoria</span><strong>${esc(t.category)}</strong></div><div><span class="muted">Valor</span><strong>${money(t.amount)}</strong></div><div><span class="muted">Data</span><strong>${formatDateKey(t.date)}</strong></div><div><span class="muted">Situação</span><strong>${isFuture(t)?"Programado":t.type==="income"?"Recebido":"Pago"}</strong></div><div><span class="muted">Recorrência</span><strong>${recurring?recLabel(t.recurrence):"Única"}</strong></div></div>${recurring?`<div class="series-box"><p class="eyebrow">SÉRIE DE RECORRÊNCIA</p><p>${s.length} lançamento(s) · ${s.filter(isFuture).length} programado(s)</p><div class="series-list">${rows}</div></div>`:""}<div class="modal-actions"><button class="btn btn-secondary" id="editOne" type="button">Editar este</button>${recurring?`<button class="btn btn-secondary" id="editSeries" type="button">Editar recorrência</button>`:""}<button class="btn btn-secondary" id="deleteTx" type="button">Excluir</button><button class="btn btn-primary modal-cancel" type="button">Fechar</button></div>`,async()=>{});$("#editOne").onclick=()=>{closeModal();txForm(t.type,t,false)};$("#editSeries")?.addEventListener("click",()=>{closeModal();txForm(t.type,t,true)});$("#deleteTx").onclick=()=>{if(confirm("Excluir esta transação?")){state.transactions=state.transactions.filter(x=>x.id!==t.id);save();closeModal();renderAll();toast("Transação excluída.")}};}

function goalForm(existing=null){openModal(existing?"Adicionar à meta":"Criar nova meta",existing?`<p class="muted">Meta: <b>${esc(existing.name)}</b></p><label>Valor a adicionar<input name="add" required inputmode="decimal"></label>`:`<label>Nome da meta<input name="name" maxlength="60" required></label><label>Valor alvo<input name="target" required inputmode="decimal"></label><label>Valor inicial<input name="current" inputmode="decimal" value="0"></label><label>Prazo<input name="deadline" type="date"></label>`,async fd=>{if(existing){const a=amount(fd.get("add"));if(!(a>0))return toast("Informe um valor válido.");const was=existing.current>=existing.target;existing.current=Math.min(existing.target,existing.current+a);if(!was&&existing.current>=existing.target){existing.completedAt=todayKey();save();closeModal();renderGoals();goalComplete(existing);return}}else{const g={id:uid("goal"),name:String(fd.get("name")||"").trim(),target:amount(fd.get("target")),current:Math.min(amount(fd.get("current")),amount(fd.get("target"))),deadline:String(fd.get("deadline")||""),openedAt:todayKey(),completedAt:""};if(!g.name||g.target<=0)return toast("Preencha nome e valor alvo.");if(g.current>=g.target)g.completedAt=todayKey();state.goals.push(g)}save();closeModal();renderGoals();});}
function goalComplete(g){const r=$("#modalRoot");r.innerHTML=`<div class="backdrop"><div class="modal glass" style="text-align:center"><div style="font-size:3rem">✓</div><p class="eyebrow">META CONCLUÍDA</p><h2>Parabéns, ${esc(state.profile.username||"amigo")}!</h2><p class="muted">Você abriu a meta <b>${esc(g.name)}</b>${g.openedAt?` em ${formatDateKey(g.openedAt)}`:""} e chegou ao objetivo.</p><button class="btn btn-primary modal-cancel" type="button">Aproveitar a conquista</button></div></div>`;r.classList.remove("hidden");lockPage(true);$(".modal-cancel",r).onclick=closeModal;}

function privacyShow(){const r=$("#privacyRoot");r.classList.remove("hidden");lockPage(true)}
function privacyAccept(){state.settings.privacyAccepted=true;save();$("#privacyRoot").classList.add("hidden");lockPage(false);openAssistant(true)}
function openAssistant(welcome=false){const r=$("#assistantRoot");r.classList.remove("hidden");lockPage(true);if(welcome&&!$("#assistantMessages").children.length)assistantSay("Olá! Eu sou o Assistente Santinho. Posso registrar suas despesas e rendas, consultar seu saldo e mostrar seus gastos. Quando faltar alguma informação, eu pergunto antes de salvar.");setTimeout(()=>$("#assistantInput")?.focus(),80);}
function closeAssistant(){try{recognition?.stop()}catch{}recognition=null;$("#assistantRoot").classList.add("hidden");lockPage(false)}
function assistantSay(t){const r=$("#assistantMessages"),p=document.createElement("div");p.className="assistant-message assistant";p.textContent=t;r.appendChild(p);r.scrollTop=r.scrollHeight}
function assistantUser(t){const r=$("#assistantMessages"),p=document.createElement("div");p.className="assistant-message user";p.textContent=t;r.appendChild(p);r.scrollTop=r.scrollHeight}
function suggestions(arr){const r=$("#assistantSuggestions");r.innerHTML=arr.map(x=>`<button class="assistant-suggestion" type="button">${esc(x)}</button>`).join("");$$(".assistant-suggestion",r).forEach(b=>b.onclick=()=>{$("#assistantInput").value=b.textContent;assistantHandle(b.textContent)});}
function detectType(t){const s=t.toLowerCase();if(/\b(gastei|paguei|despesa|gasto|comprei|comprei)\b/.test(s))return"expense";if(/\b(recebi|ganhei|salário|salario|renda|entrada|entrou)\b/.test(s))return"income";return"";}
function parseAmount(t){let s=String(t).toLowerCase().replace(/milhão/g,"1000000").replace(/milhao/g,"1000000"),m=s.match(/(?:r\$\s*)?(\d+(?:[.,]\d+)?)\s*(mil|milhão|milhao)?\s*(?:reais?|rs)?/i);if(!m)return 0;let n=Number(m[1].replace(/\./g,"").replace(",","."));if(m[2]&&m[2].toLowerCase().startsWith("mil"))n*=1000;return Number.isFinite(n)?n:0;}
function parseDate(t){const s=t.toLowerCase(),now=new Date();if(/\bhoje\b/.test(s))return todayKey();if(/\bontem\b/.test(s)){now.setDate(now.getDate()-1);return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;}const m=s.match(/\b(\d{1,2})[\/.-](\d{1,2})(?:[\/.-](\d{2,4}))?\b/);if(!m)return"";let y=m[3]?Number(m[3]):now.getFullYear();if(y<100)y+=2000;const d=String(Number(m[1])).padStart(2,"0"),mo=String(Number(m[2])).padStart(2,"0");return `${y}-${mo}-${d}`;}
function parseRec(t){const s=t.toLowerCase();if(/\b(não repetir|nao repetir|uma vez|única|unica|não se repete|nao se repete)\b/.test(s))return"none";if(/\b(diária|diaria|todo dia|diariamente)\b/.test(s))return"daily";if(/\b(semanal|semanalmente|toda semana)\b/.test(s))return"weekly";if(/\b(quinzenal|a cada 15 dias)\b/.test(s))return"biweekly";if(/\b(mensal|mensalmente|todo mês|todo mes)\b/.test(s))return"monthly";return"";}
function parseCat(t){const s=t.toLowerCase();const map=[["Alimentação",/alimenta|mercado|comida|restaurante|lanche/],["Transporte",/transporte|uber|gasolina|ônibus|onibus|combustível|combustivel/],["Moradia",/moradia|aluguel|luz|água|agua|condomínio|condominio/],["Lazer",/lazer|cinema|jogo|bar|passeio/],["Estudos",/estudo|faculdade|curso|livro/],["Saúde",/saúde|saude|farmácia|farmacia|médico|medico/],["Assinaturas",/netflix|spotify|prime|disney|youtube|assinatura/],["Salário",/salário|salario|pagamento|ordenado/],["Freelance",/freela|freelance|cliente|projeto/],["Investimentos",/investimento|cdb|tesouro|ações|acoes/]];return map.find(x=>x[1].test(s))?.[0]||"";}
function cleanDescription(t){return String(t).replace(/r\$\s*[\d.,]+/gi," ").replace(/\b[\d.,]+\s*(?:reais?|rs)\b/gi," ").replace(/\b(gastei|paguei|recebi|ganhei|registrar|registre|adicione|adicionar|despesa|gasto|renda|entrada|hoje|ontem|uma vez|não repetir|nao repetir|diária|diaria|semanal|quinzenal|mensal|mensalmente|semanalmente)\b/gi," ").replace(/\b\d{1,2}[\/.-]\d{1,2}(?:[\/.-]\d{2,4})?\b/g," ").replace(/\s+/g," ").trim();}
function parsed(t){return{type:detectType(t),description:cleanDescription(t),amount:parseAmount(t),date:parseDate(t),category:parseCat(t),recurrence:parseRec(t)};}
function missing(){const d=assistant.draft;if(!d.type)return["type","Você quer registrar uma **despesa** ou uma **renda**?"];if(!d.description)return["description","Qual é o **nome ou descrição** da despesa/renda?"];if(!(d.amount>0))return["amount","Qual foi o **valor**?"];if(!d.date)return["date","Em qual **data** aconteceu? Pode dizer “hoje”, “ontem” ou 25/09."];if(!d.category)return["category","Qual é a **categoria**? Ex.: Alimentação, Transporte, Moradia ou Outra."];if(!d.recurrence)return["recurrence","Essa movimentação é **uma vez** ou tem recorrência? Pode ser diária, semanal, quinzenal ou mensal."];if(d.recurrence!=="none"&&!d.recurrenceEnd)return["recurrenceEnd","Até quando devo repetir? Diga uma data, por exemplo 31/12/2026."];return["",""];}
function draftSummary(){const d=assistant.draft;return`Entendi assim:\n\n• Tipo: ${d.type==="income"?"Renda":"Despesa"}\n• Nome/descrição: ${d.description}\n• Valor: ${money(d.amount)}\n• Data: ${formatDateKey(d.date)}\n• Categoria: ${d.category}\n• Recorrência: ${d.recurrence==="none"?"Uma vez":recLabel(d.recurrence)}${d.recurrence!=="none"?`\n• Até: ${formatDateKey(d.recurrenceEnd)}`:""}\n\nEstá tudo certo?`;}
function assistantCommit(){const d=assistant.draft,miss=missing();if(miss[0])return assistantSay(miss[1]);const occ=buildOccurrences(d.date,d.recurrence,d.recurrenceEnd),rid=d.recurrence==="none"?null:uid("txseries");occ.forEach(date=>state.transactions.push({id:uid("tx"),type:d.type,description:d.description,amount:d.amount,category:d.category,date,note:"Lançado pelo Assistente Santinho",recurrence:d.recurrence,recurrenceEnd:d.recurrence==="none"?"":d.recurrenceEnd,parentId:null,recurrenceId:rid}));save();renderAll();const total=d.amount*occ.length;assistant.draft=null;assistant.awaiting=null;assistant.confirm=false;assistantSay(occ.length>1?`Pronto. Registrei ${occ.length} lançamentos de ${d.description}, totalizando ${money(total)}.`:`Pronto. Registrei ${d.description} como ${d.type==="income"?"renda":"despesa"} de ${money(d.amount)} em ${formatDateKey(d.date)}.`);suggestions(["Quanto tenho disponível?","Quanto gastei este mês?","Registrar outro gasto"]);}
function assistantApply(text){const p=parsed(text),d=assistant.draft||{};if(!d.type&&p.type)d.type=p.type;if(!d.description&&p.description)d.description=p.description;if(!(d.amount>0)&&p.amount)d.amount=p.amount;if(!d.date&&p.date)d.date=p.date;if(!d.category&&p.category)d.category=p.category;if(!d.recurrence&&p.recurrence)d.recurrence=p.recurrence;if(assistant.awaiting==="type"){const x=detectType(text);if(x)d.type=x}else if(assistant.awaiting==="description")d.description=text.trim();else if(assistant.awaiting==="amount"){const x=parseAmount(text);if(x)d.amount=x}else if(assistant.awaiting==="date"){const x=parseDate(text);if(x)d.date=x}else if(assistant.awaiting==="category"){d.category=parseCat(text)||(/^outr[oa]s?$/i.test(text.trim())?"Outros":"")}else if(assistant.awaiting==="recurrence"){d.recurrence=parseRec(text)||(/^uma vez$/i.test(text.trim())?"none":"")}else if(assistant.awaiting==="recurrenceEnd"){const x=parseDate(text);if(x)d.recurrenceEnd=x}assistant.draft=d;assistant.awaiting=null;}
function queryAnswer(t){const s=t.toLowerCase(),tt=totals(),free=available(),sched=scheduledExpenses(),month=todayKey().slice(0,7),m=state.transactions.filter(x=>monthKey(x.date)===month&&realized(x));if(/saldo|disponível|disponivel|quanto tenho|quanto sobra/.test(s))return`Seu saldo acumulado é ${money(tt.balance)}.\nDespesas programadas: ${money(sched)}.\nDisponível considerando as programadas: ${money(free)}.`;if(/programad/.test(s)){const x=state.transactions.filter(q=>isFuture(q)&&q.type==="expense").sort((a,b)=>cmp(a.date,b.date));return x.length?`Você tem ${x.length} despesa(s) programada(s), somando ${money(sched)}:\n\n${x.slice(0,10).map(q=>`• ${formatDateKey(q.date)} — ${q.description}: ${money(q.amount)}`).join("\n")}`:"Você não tem despesas programadas."}if(/gasto|despesa/.test(s)){const x=m.filter(q=>q.type==="expense"),sum=x.reduce((a,b)=>a+b.amount,0);return`Neste mês você realizou ${x.length} despesa(s), totalizando ${money(sum)}.`}if(/receb|entrada/.test(s)){const x=m.filter(q=>q.type==="income"),sum=x.reduce((a,b)=>a+b.amount,0);return`Neste mês você recebeu ${money(sum)} em entradas.`}return"Posso consultar saldo, gastos e despesas programadas, ou registrar uma movimentação.";}
function isQuery(t){return/\b(quanto|qual|quais|mostre|saldo|disponível|disponivel|gastei este mês|gastei este mes|gastos|programadas|programados)\b/i.test(t);}
function assistantHandle(raw){const text=String(raw||"").trim();if(!text)return;$("#assistantInput").value="";assistantUser(text);if(assistant.confirm){if(/^(sim|pode|confirmo|registrar|correto|isso)$/i.test(text))return assistantCommit();if(/^(não|nao|cancelar|corrigir)$/i.test(text)){assistant.confirm=false;assistantSay("Tudo bem. Me diga o que quer corrigir.");return}assistantApply(text)}else if(!assistant.draft&&isQuery(text)){assistantSay(queryAnswer(text));return suggestions(["Quanto tenho disponível?","Quanto gastei este mês?","Registrar um gasto"]);}else{if(!assistant.draft)assistant.draft={type:"",description:"",amount:0,date:"",category:"",recurrence:"",recurrenceEnd:""};assistantApply(text)}const [field,msg]=missing();if(field){assistant.awaiting=field;assistantSay(msg);return suggestions(field==="type"?["Despesa","Renda"]:field==="category"?["Alimentação","Transporte","Outros"]:field==="recurrence"?["Uma vez","Mensal","Semanal"]:field==="date"?["Hoje","Ontem"]:field==="amount"?["R$ 35","R$ 120,50"]:["31/12/2026"]);}assistant.confirm=true;assistantSay(draftSummary());suggestions(["Sim, registrar","Corrigir","Cancelar"]);}

function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return assistantSay("O reconhecimento de voz não está disponível neste navegador. Continue por texto e eu funcionarei normalmente.");if(recognition){try{recognition.stop()}catch{}recognition=null;return}recognition=new R();recognition.lang="pt-BR";recognition.interimResults=false;recognition.maxAlternatives=1;$("#assistantMic").style.opacity=".6";assistantSay("Pode falar. Estou ouvindo...");recognition.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||"";recognition=null;$("#assistantMic").style.opacity="1";assistantHandle(text)};recognition.onerror=()=>{recognition=null;$("#assistantMic").style.opacity="1";assistantSay("Não consegui ouvir. Tente novamente ou escreva.");};recognition.onend=()=>{recognition=null;$("#assistantMic").style.opacity="1"};try{recognition.start()}catch{recognition=null;$("#assistantMic").style.opacity="1";assistantSay("Não consegui iniciar o microfone. Continue por texto.");}}

function configurePin(){if(state.settings.pinHash)return openModal("Alterar PIN",`<label>PIN atual<input name="old" type="password" inputmode="numeric" maxlength="6" required></label><label>Novo PIN<input name="pin" type="password" inputmode="numeric" minlength="4" maxlength="6" required></label>`,async fd=>{const old=String(fd.get("old")||""),pin=String(fd.get("pin")||"");if(!/^\d{4,6}$/.test(pin))return toast("PIN inválido.");if(await hash(old,state.settings.pinHash.salt)!==state.settings.pinHash.hash)return toast("PIN atual incorreto.");const salt=crypto.randomUUID();state.settings.pinHash={salt,hash:await hash(pin,salt)};save();closeModal();renderProfile();toast("PIN alterado.")});openModal("Configurar PIN",`<label>Novo PIN<input name="pin" type="password" inputmode="numeric" minlength="4" maxlength="6" required></label>`,async fd=>{const pin=String(fd.get("pin")||"");if(!/^\d{4,6}$/.test(pin))return toast("PIN inválido.");const salt=crypto.randomUUID();state.settings.pinHash={salt,hash:await hash(pin,salt)};save();closeModal();renderProfile();toast("PIN ativado.")});}

function backup(){const blob=new Blob([JSON.stringify({app:"Santinho Finance",version:2,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),file=new File([blob],`santinho-finance-backup-${todayKey()}.json`,{type:"application/json"});(async()=>{try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))await navigator.share({title:"Backup Santinho Finance",files:[file]});else{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}state.settings.lastBackupAt=new Date().toISOString();save();renderProfile();$("#backupStatus").textContent="Backup concluído."}catch(e){$("#backupStatus").textContent=e?.name==="AbortError"?"Compartilhamento cancelado.":"Não foi possível criar o backup."}})();}
async function restore(file){if(!file)return;try{const x=JSON.parse(await file.text());if(x?.app!=="Santinho Finance"||!x?.data)throw 0;if(!confirm("Restaurar este backup substituirá os dados locais atuais. Continuar?"))return;state=normalize(x.data);save();renderAll();toast("Backup restaurado.")}catch{$("#backupStatus").textContent="Arquivo inválido ou corrompido."}finally{$("#restoreInput").value=""}}
function imageBase64(file){return new Promise((res,rej)=>{if(!file?.type?.startsWith("image/"))return rej();const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}

function rowsForYear(year){return state.transactions.filter(t=>yearKey(t.date)===year&&realized(t));}
function exportTXT(){const y=$("#analysisYear").value||todayKey().slice(0,4),tx=rowsForYear(y);const out=[`SANTINHO FINANCE — ${y}`,"",`Entradas: ${money(tx.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0))}`,`Despesas: ${money(tx.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0))}`,"","TRANSAÇÕES",...tx.sort((a,b)=>cmp(a.date,b.date)).map(t=>`${formatDateKey(t.date)} | ${t.type==="income"?"RENDA":"DESPESA"} | ${t.description} | ${t.category} | ${money(t.amount)}`)].join("\n");download(new Blob([out],{type:"text/plain;charset=utf-8"}),`santinho-finance-${y}.txt`);}
function printPDF(){const y=$("#analysisYear").value||todayKey().slice(0,4),tx=rowsForYear(y);const w=window.open("","_blank");if(!w)return toast("Permita pop-ups para gerar o PDF.");w.document.write(`<html><head><title>Santinho Finance ${y}</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>Santinho Finance — ${y}</h1><table><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Categoria</th><th>Valor</th></tr>${tx.map(t=>`<tr><td>${formatDateKey(t.date)}</td><td>${t.type}</td><td>${esc(t.description)}</td><td>${esc(t.category)}</td><td>${money(t.amount)}</td></tr>`).join("")}</table><script>window.onload=()=>window.print();<\/script></body></html>`);w.document.close();}
function crc32(bytes){let c=~0;for(let n of bytes){c^=n;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(~c)>>>0;}
function zipStore(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;for(const [name,text] of files){const nb=enc.encode(name),data=enc.encode(text),crc=crc32(data),local=new Uint8Array(30+nb.length+data.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(8,0,true);v.setUint32(18,crc,true);v.setUint32(22,data.length,true);v.setUint32(26,nb.length,true);local.set(nb,30);local.set(data,30+nb.length);parts.push(local);const cd=new Uint8Array(46+nb.length),d=new DataView(cd.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,nb.length,true);d.setUint32(42,offset,true);cd.set(nb,46);central.push(cd);offset+=local.length}const centralSize=central.reduce((s,x)=>s+x.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});}
function xlsx(){const y=$("#analysisYear").value||todayKey().slice(0,4),tx=rowsForYear(y),rows=[["Data","Tipo","Descrição","Categoria","Valor"],...tx.map(t=>[formatDateKey(t.date),t.type==="income"?"Renda":"Despesa",t.description,t.category,t.amount])];const escx=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");const sheet=rows.map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>typeof v==="number"?`<c r="${String.fromCharCode(65+j)}${i+1}"><v>${v}</v></c>`:`<c r="${String.fromCharCode(65+j)}${i+1}" t="inlineStr"><is><t>${escx(v)}</t></is></c>`).join("")}</row>`).join("");const files=[["[Content_Types].xml",`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`],["_rels/.rels",`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`],["xl/workbook.xml",`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Transações" sheetId="1" r:id="rId1"/></sheets></workbook>`],["xl/_rels/workbook.xml.rels",`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`],["xl/worksheets/sheet1.xml",`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`]];download(zipStore(files),`santinho-finance-${y}.xlsx`);}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200);}

function bind(){syncViewport();window.addEventListener("resize",syncViewport,{passive:true});window.visualViewport?.addEventListener("resize",syncViewport,{passive:true});
$("#toggleSetup").onclick=()=>authForm($("#setupForm").classList.contains("hidden")?"setup":"login");$("#setupForm").onsubmit=setup;$("#loginForm").onsubmit=login;$("#pinForm").onsubmit=verifyPin;$("#logoutFromPin").onclick=logout;$("#lockNow").onclick=lock;$("#mobileBrand").onclick=()=>navigate("dashboard");$$("[data-nav]").forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
$("#addExpense").onclick=()=>txForm("expense");$("#addIncome").onclick=()=>txForm("income");$("#addTransactionTop").onclick=()=>txForm("expense");$("#toggleBalance").onclick=()=>{balanceVisible=!balanceVisible;renderDashboard()};$("#transactionSearch").oninput=renderTransactions;$("#transactionType").onchange=renderTransactions;$("#transactionStatus").onchange=renderTransactions;$("#analysisYear").onchange=renderAnalysis;$("#analysisMonth").onchange=renderAnalysis;
$("#addGoal").onclick=()=>goalForm();$("#themeSelect").onchange=e=>{changeTheme(e.target.value);toast("Tema atualizado.")};$("#configurePin").onclick=configurePin;$("#saveProfile").onclick=()=>{const u=$("#profileUsername").value.trim();if(!u)return toast("Informe um nome de usuário.");state.profile.username=u;state.profile.email=$("#profileEmail").value.trim();save();renderDashboard();toast("Perfil salvo.")};
$("#profilePhoto").onchange=async e=>{try{const d=await imageBase64(e.target.files?.[0]);if(d.length>3000000)return toast("Escolha uma imagem menor.");state.profile.avatar=d;save();renderProfile();renderDashboard();toast("Foto atualizada.")}catch{toast("Não foi possível ler a imagem.")}};
$("#backupNow").onclick=backup;$("#restoreData").onclick=()=>$("#restoreInput").click();$("#restoreInput").onchange=e=>restore(e.target.files?.[0]);$("#logout").onclick=logout;$("#exportTxt").onclick=exportTXT;$("#exportPdf").onclick=printPDF;$("#exportXlsx").onclick=xlsx;
$("#voiceAssistant").onclick=()=>openAssistant(false);$("#assistantClose").onclick=closeAssistant;$("#assistantMic").onclick=startVoice;$("#assistantInputForm").onsubmit=e=>{e.preventDefault();assistantHandle($("#assistantInput").value)};$("#assistantRoot").onclick=e=>{if(e.target.classList.contains("backdrop"))closeAssistant()};$("#privacyAccept").onclick=privacyAccept;
document.addEventListener("click",e=>{const tx=e.target.closest("[data-open-tx]");if(tx){txDetails(tx.dataset.openTx);return}const gd=e.target.closest("[data-goal-del]");if(gd){if(confirm("Excluir esta meta?")){state.goals=state.goals.filter(g=>g.id!==gd.dataset.goalDel);save();renderGoals()};return}const ga=e.target.closest("[data-goal-add]");if(ga){const g=state.goals.find(x=>x.id===ga.dataset.goalAdd);if(g)goalForm(g)}});}

async function init(){bind();try{await loadState();authMode();show("authView");if(!state.credentials)authForm("setup");if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});}catch{authMsg("O aplicativo encontrou um erro ao iniciar. Seus dados locais não foram apagados.",true)}}
init();
})();